### ISSUE TITLE
validation of string format uri wrongly fails with relative pathes

### ISSUE THREAD

**Issue by neongrau** [ahx/openapi_first#244]
Just ran across some new issue during response validation

> Response body is invalid: value at `/data/attributes/image` does not match format: uri

According to OpenAPI https://spec.openapis.org/registry/format/uri
they refer to https://www.rfc-editor.org/rfc/rfc3986.html which allow relative pathes.

Same stated explicitly at https://swagger.io/specification/

Or am i misinterpreting something?

**Comment by ahx** [comment]
I think you are looking for uri-reference not uri https://json-schema.org/understanding-json-schema/reference/string

**Comment by neongrau** [comment]
Not really. The field usually refers to an S3 URL. But if not set, it defaults to a local placeholder. I could change to an absolute URL though OpenAPI says the local relative URL is good.

**Comment by ahx** [comment]
I think you are are right. I have tried two ([1](https://json-everything.net/json-schema/), [2](https://json-schema.hyperjump.io/)) other schema validation libraries and they indeed seem to behave differently from json_schemer in this case.

```ruby
irb(main):004> JSONSchemer.schema({'type' => 'string', 'format' => 'uri' }, meta_schema: 'https://spec.openapis.org/oas/3.1/dialect/base').valid?('/data/foo/bar')
=> false

irb(main):006> JSONSchemer.schema({'type' => 'string', 'format' => 'uri-reference' }, meta_schema: 'https://spec.openapis.org/oas/3.1/dialect/base').valid?('/data/foo/bar')
=> true
```

I am not json_schemer is wrong here, though since [this section of the JSON Schema spec](https://json-schema.org/draft/2020-12/json-schema-validation#section-7.3.5) does not really clarify things for me.

**Comment by neongrau** [comment]
Just ran across this https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.0.2.md#relative-references-in-urls
