### ISSUE TITLE
Convert `format: 'date'`, `format: 'date-time'` to Ruby objects

### ISSUE THREAD

**Issue by ahx** [ahx/openapi_first#98]
Let's parse 'date', 'date-time' and 'time' formats.

Convert 'date'  to `Date`, 'date-time' to `Time` and 'time' to `Time` with `1970-01-01`. Cool?

**Comment by supermomonga** [comment]
@ahx I think It would be nice If we can use custom converter for it.

e.g.) `date-time` is ISO8601 format, and it contains timezone. so I want to write custom converter that converts value to `ActiveSupport::TimeWithZone` instance.

**Comment by ahx** [comment]
Hi @supermomonga! I still think it is not a bad Idea to add some (customizable) way to convert incoming data. 
Please just re-open this issue if you think this should be added to the library.

Do you have an API in mind how to configure such a feature?

**Comment by supermomonga** [comment]
@ahx Thanks! Yes, I believe it would be very useful if this feature were implemented.
I am currently working on a gem for Rails that uses the OpenAPI spec to provide validation and coercion of request parameters, and also provides staticaly typing (RBS generation) for them.

Since it internally utilizes the `openapi_first` gem, having custom converters available for coercion would be very useful, as it would allow me to implement coercion to Rails' standard datetime class `ActiveSupport::TimeWithZone`.

Should I create separate new issue in the context of more generic custom converters rather than an issue specific to 'date' or 'date-time'?

**Comment by ahx** [comment]
> Should I create separate new issue in the context of more generic custom converters rather than an issue specific to 'date' or 'date-time'?

Yes, let's create a new issue or a new [discussion](https://github.com/ahx/openapi_first/discussions). Thank you.

**Comment by supermomonga** [comment]
@ahx

sorry, was away for a while due to vacations. I have created a new discussion! https://github.com/ahx/openapi_first/discussions/207
